name: pow

channels:
  - conda-forge
  - defaults

dependencies:
  - python>=3.7,<3.8
  - folium=0.12.0
  - jupyter=1.0.0
  - scikit-learn=1.0
  - pandas=1.3.4
  - plotly=5.3.1
  - pyarrow=5.0.0
  - pip  
  - pip:    
    - git+https://gitlab.inria.fr/spicy/pow-api.git
